apiVersion: elastic.iml.github.io/v1alpha1
kind: ScalePlan
metadata:
  name: deepctr-auto-scaling-job-01
  labels:
    elasticjob-name: deepctr-auto-scale
    scale-type: manual
spec:
  ownerJob: deepctr-auto-scale
  replicaResourceSpecs:
    ps:
      replicas: 3